name: docker
services:
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
  golang:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_CONNECTION_STRING=redis:6379
    depends_on:
      - redis